# setup-ansible-env.yml
---
- name: Setup for the Ansible's Environment
  hosts: localhost
  gather_facts: no
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: Add "/ect/ansible/hosts"
      blockinfile:
        path: /etc/ansible/hosts
        block: |
            [rancher]
            192.168.1.1
            192.168.1.2
            192.168.1.3
            [ansible]
            192.168.1.10
            [all:vars]
            ansible_python_interpreter=/usr/bin/python3

    - name: Configure Bashrc
      lineinfile:
        path: /home/vagrant/.bashrc
        line: "{{ item }}"
      with_items:
        - "alias ans='ansible'"
        - "alias anp='ansible-playbook'"
        - "alias ang='ansible-galaxy'"

    - name: Check exist /usr/bin/python
      stat:
        path: "/usr/bin/python"
      register: python_status

    - name: Create a python symbolic link for python3
      file:
        src: /usr/bin/python3
        dest: /usr/bin/python
        state: link
      when: not python_status.stat.exists

